<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

class UserTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $now = Carbon::now('Asia/Ho_Chi_Minh')->toDateTimeString();
        DB::table('users')->insert([
            [

                'email' => 'admin@hblab.vn',
                'name' => 'Admin',
                'id_user' => 'admin',
                'password' => Hash::make('123456'),
                'department_id' => 1,
                'role_id' => 1,
                'status' => 1,
                'created_at' => $now,
                'updated_at' =>  $now,
                'deleted_at' => null,
            ],
             [

                'email' => 'giangnt@hblab.vn',
                'name' => 'Nguyễn Trường Giang',
                'id_user' => 'giangnt',
                'password' => Hash::make('123456'),
                'department_id' => 1,
                'role_id' => 1,
                'status' => 1,
                'created_at' => $now,
                'updated_at' =>  $now,
                'deleted_at' => null,
             ],
             [

                'email' => 'tuyentx@hblab.vn',
                'name' => 'Trần Xuân Tuyên',
                'id_user' => 'tuyentx',
                'password' => Hash::make('123456'),
                'department_id' => 1,
                'role_id' => 1,
                'status' => 1,
                'created_at' => $now,
                'updated_at' =>  $now,
                'deleted_at' => null,
             ],
             [

                'email' => 'phuongtm@hblab.vn',
                'name' => 'Trần Minh Phương',
                'id_user' => 'phuongtm',
                'password' => Hash::make('123456'),
                'department_id' => 1,
                'role_id' => 1,
                'status' => 1,
                'created_at' => $now,
                'updated_at' =>  $now,
                'deleted_at' => null,
             ],
             [

                'email' => 'hieunh@hblab.vn',
                'name' => 'Nguyễn Hữu Hiếu',
                'id_user' => 'hieunh',
                'password' => Hash::make('123456'),
                'department_id' => 1,
                'role_id' => 1,
                'status' => 1,
                'created_at' => $now,
                'updated_at' =>  $now,
                'deleted_at' => null,
             ],
             [

                'email' => 'hainv@hblab.vn',
                'name' => 'Ngô Văn Hải',
                'id_user' => 'hainv',
                'password' => Hash::make('123456'),
                'department_id' => 2,
                'role_id' => 2,
                'status' => 1,
                'created_at' => $now,
                'updated_at' =>  $now,
                'deleted_at' => null,
             ],
             [

                'email' => 'vinhnt@hblab.vn',
                'name' => 'Nguyễn Thiện Vinh',
                'id_user' => 'vinhnt',
                'password' => Hash::make('123456'),
                'department_id' => 2,
                'role_id' => 3,
                'status' => 1,
                'created_at' => $now,
                'updated_at' =>  $now,
                'deleted_at' => null,
             ],
             [

                'email' => 'trangtt@hblab.vn',
                'name' => 'Thái Thị Trang',
                'id_user' => 'trangtt',
                'password' => Hash::make('123456'),
                'department_id' => 3,
                'role_id' => 3,
                'status' => 1,
                'created_at' => $now,
                'updated_at' =>  $now,
                'deleted_at' => null,
             ],
             [

                'email' => 'dieppv@hblab.vn',
                'name' => 'Phùng Văn Điệp',
                'id_user' => 'dieppv',
                'password' => Hash::make('123456'),
                'department_id' => 2,
                'role_id' => 3,
                'status' => 1,
                'created_at' => $now,
                'updated_at' =>  $now,
                'deleted_at' => null,
             ],
             [

                'email' => 'namnv@hblab.vn',
                'name' => 'Nguyễn Văn Nam',
                'id_user' => 'namnv',
                'password' => Hash::make('123456'),
                'department_id' => 3,
                'role_id' => 3,
                'status' => 1,
                'created_at' => $now,
                'updated_at' =>  $now,
                'deleted_at' => null,
             ],
             [
                'email' => 'vuht@hblab.vn',
                'name' => 'Hoàng Thái Vũ',
                'id_user' => 'vuht',
                'password' => Hash::make('123456'),
                'department_id' => 4,
                'role_id' => 3,
                'status' => 1,
                'created_at' => $now,
                'updated_at' =>  $now,
                'deleted_at' => null,
             ],
             [
               'email' => 'huylt@hblab.vn',
               'name' => 'Lê Thanh Huy',
               'id_user' => 'huylt',
               'password' => Hash::make('123456'),
               'department_id' => 5,
               'role_id' => 3,
               'status' => 1,
               'created_at' => $now,
               'updated_at' =>  $now,
               'deleted_at' => null,
            ],
            [
               'email' => 'trangpt@hblab.vn',
               'name' => 'Phạm Thị Trang',
               'id_user' => 'trangpt',
               'password' => Hash::make('123456'),
               'department_id' => 3,
               'role_id' => 2,
               'status' => 1,
               'created_at' => $now,
               'updated_at' =>  $now,
               'deleted_at' => null,
            ],
            [
               'email' => 'datnn@hblab.vn',
               'name' => 'Nguyễn Ngọc Đạt',
               'id_user' => 'datnn',
               'password' => Hash::make('123456'),
               'department_id' => 5,
               'role_id' => 3,
               'status' => 1,
               'created_at' => $now,
               'updated_at' =>  $now,
               'deleted_at' => null,
            ],
            [
               'email' => 'huylh@hblab.vn',
               'name' => 'Lê Hồng Huy',
               'id_user' => 'huylh',
               'password' => Hash::make('123456'),
               'department_id' => 4,
               'role_id' => 3,
               'status' => 1,
               'created_at' => $now,
               'updated_at' =>  $now,
               'deleted_at' => null,
            ],
            [
               'email' => 'hungdq@hblab.vn',
               'name' => 'Đặng Quang Hưng',
               'id_user' => 'hungdq',
               'password' => Hash::make('123456'),
               'department_id' => 5,
               'role_id' => 3,
               'status' => 1,
               'created_at' => $now,
               'updated_at' =>  $now,
               'deleted_at' => null,
            ],
            [
               'email' => 'hant@hblab.vn',
               'name' => 'Nguyễn Thanh Hà',
               'id_user' => 'hant',
               'password' => Hash::make('123456'),
               'department_id' => 4,
               'role_id' => 2,
               'status' => 1,
               'created_at' => $now,
               'updated_at' =>  $now,
               'deleted_at' => null,
            ],
            [
               'email' => 'hangnt@hblab.vn',
               'name' => 'Nguyễn Thúy Hằng',
               'id_user' => 'hangnt',
               'password' => Hash::make('123456'),
               'department_id' => 2,
               'role_id' => 3,
               'status' => 1,
               'created_at' => $now,
               'updated_at' =>  $now,
               'deleted_at' => null,
            ],
            [
               'email' => 'duongnt@hblab.vn',
               'name' => 'Nguyễn Thùy Dương',
               'id_user' => 'dungnt',
               'password' => Hash::make('123456'),
               'department_id' => 3,
               'role_id' => 3,
               'status' => 1,
               'created_at' => $now,
               'updated_at' =>  $now,
               'deleted_at' => null,
            ],
            [
               'email' => 'chiennv@hblab.vn',
               'name' => 'Nguyễn Văn Chiến',
               'id_user' => 'chiennv',
               'password' => Hash::make('123456'),
               'department_id' => 5,
               'role_id' => 2,
               'status' => 1,
               'created_at' => $now,
               'updated_at' =>  $now,
               'deleted_at' => null,
            ],
            [
               'email' => 'nghiemnv@hblab.vn',
               'name' => 'Nguyễn Vũ Nghiêm',
               'id_user' => 'nghiemnv',
               'password' => Hash::make('123456'),
               'department_id' => 2,
               'role_id' => 2,
               'status' => 1,
               'created_at' => $now,
               'updated_at' =>  $now,
               'deleted_at' => null,
            ],
            [
               'email' => 'duynp@hblab.vn',
               'name' => 'Nguyễn Phương Duy',
               'id_user' => 'duynp',
               'password' => Hash::make('123456'),
               'department_id' => 4,
               'role_id' => 3,
               'status' => 1,
               'created_at' => $now,
               'updated_at' =>  $now,
               'deleted_at' => null,
            ],
            [
               'email' => 'duyennp@hblab.vn',
               'name' => 'Nguyễn Phương Duyên',
               'id_user' => 'duyennp',
               'password' => Hash::make('123456'),
               'department_id' => 3,
               'role_id' => 3,
               'status' => 1,
               'created_at' => $now,
               'updated_at' =>  $now,
               'deleted_at' => null,
            ],
            [
               'email' => 'phuongnb@hblab.vn',
               'name' => 'Nguyễn Bích Phượng',
               'id_user' => 'phuongnb',
               'password' => Hash::make('123456'),
               'department_id' => 4,
               'role_id' => 3,
               'status' => 1,
               'created_at' => $now,
               'updated_at' =>  $now,
               'deleted_at' => null,
            ],
            [
               'email' => 'phongnb@hblab.vn',
               'name' => 'Nguyễn Ngọc Phong',
               'id_user' => 'phongnb',
               'password' => Hash::make('123456'),
               'department_id' => 2,
               'role_id' => 3,
               'status' => 1,
               'created_at' => $now,
               'updated_at' =>  $now,
               'deleted_at' => null,
            ],
            [
               'email' => 'hoangnt@hblab.vn',
               'name' => 'Nguyễn Trọng Hoàng',
               'id_user' => 'hoangnt',
               'password' => Hash::make('123456'),
               'department_id' => 5,
               'role_id' => 3,
               'status' => 1,
               'created_at' => $now,
               'updated_at' =>  $now,
               'deleted_at' => null,
            ],
            [
               'email' => 'nghiabc@hblab.vn',
               'name' => 'Bạch Chí Nghĩa',
               'id_user' => 'nghiabc',
               'password' => Hash::make('123456'),
               'department_id' => 2,
               'role_id' => 3,
               'status' => 1,
               'created_at' => $now,
               'updated_at' =>  $now,
               'deleted_at' => null,
            ],
            [
               'email' => 'khanhnv@hblab.vn',
               'name' => 'Nguyễn Văn Khánh',
               'id_user' => 'khanhnv',
               'password' => Hash::make('123456'),
               'department_id' => 4,
               'role_id' => 3,
               'status' => 1,
               'created_at' => $now,
               'updated_at' =>  $now,
               'deleted_at' => null,
            ],
            [
               'email' => 'hieunv@hblab.vn',
               'name' => 'Nguyễn Ngọc Hiếu',
               'id_user' => 'hieunv',
               'password' => Hash::make('123456'),
               'department_id' => 5,
               'role_id' => 3,
               'status' => 1,
               'created_at' => $now,
               'updated_at' =>  $now,
               'deleted_at' => null,
            ],
            [
               'email' => 'trungpq@hblab.vn',
               'name' => 'Phạm Quốc Trung',
               'id_user' => 'trungpq',
               'password' => Hash::make('123456'),
               'department_id' => 2,
               'role_id' => 3,
               'status' => 1,
               'created_at' => $now,
               'updated_at' =>  $now,
               'deleted_at' => null,
            ],
        ]);
    }
}
